import React, { useState } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ActivityIndicator } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useTheme } from '../contexts/ThemeContext';
import { ArticleSummary } from '../services/summaryService';

interface SummaryCardProps {
  summary: ArticleSummary | null;
  loading?: boolean;
  onGenerate?: () => void;
  compact?: boolean;
  showReadingTime?: boolean;
}

export const SummaryCard: React.FC<SummaryCardProps> = ({
  summary,
  loading = false,
  onGenerate,
  compact = false,
  showReadingTime = true,
}) => {
  const { theme } = useTheme();
  const [expanded, setExpanded] = useState(!compact);

  if (loading) {
    return (
      <View style={[styles.card, { backgroundColor: theme.card }]}>
        <View style={styles.loadingContainer}>
          <ActivityIndicator size="small" color={theme.primary} />
          <Text style={[styles.loadingText, { color: theme.textSecondary }]}>
            Generating summary...
          </Text>
        </View>
      </View>
    );
  }

  if (!summary) {
    return (
      <View style={[styles.card, { backgroundColor: theme.card }]}>
        <View style={styles.emptyContainer}>
          <Ionicons name="document-text-outline" size={32} color={theme.textSecondary} />
          <Text style={[styles.emptyText, { color: theme.textSecondary }]}>
            No summary available
          </Text>
          {onGenerate && (
            <TouchableOpacity
              style={[styles.generateButton, { backgroundColor: theme.primary }]}
              onPress={onGenerate}
              activeOpacity={0.7}
            >
              <Ionicons name="sparkles" size={16} color="#FFFFFF" />
              <Text style={styles.generateButtonText}>Generate AI Summary</Text>
            </TouchableOpacity>
          )}
        </View>
      </View>
    );
  }

  const isAIGenerated = summary.model !== 'fallback';

  return (
    <View style={[styles.card, { backgroundColor: theme.card }]}>
      {/* Header */}
      <View style={styles.header}>
        <View style={styles.headerLeft}>
          <Ionicons 
            name={isAIGenerated ? 'sparkles' : 'document-text'} 
            size={20} 
            color={isAIGenerated ? '#FFD700' : theme.primary} 
          />
          <Text style={[styles.headerTitle, { color: theme.text }]}>
            {isAIGenerated ? 'AI Summary' : 'Quick Summary'}
          </Text>
        </View>
        <View style={styles.headerRight}>
          {showReadingTime && (
            <View style={[styles.readingTimeBadge, { backgroundColor: theme.background }]}>
              <Ionicons name="time-outline" size={14} color={theme.textSecondary} />
              <Text style={[styles.readingTimeText, { color: theme.textSecondary }]}>
                {summary.readingTime} min
              </Text>
            </View>
          )}
          {compact && (
            <TouchableOpacity
              onPress={() => setExpanded(!expanded)}
              hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}
            >
              <Ionicons 
                name={expanded ? 'chevron-up' : 'chevron-down'} 
                size={20} 
                color={theme.textSecondary} 
              />
            </TouchableOpacity>
          )}
        </View>
      </View>

      {/* TL;DR */}
      {expanded && (
        <>
          <View style={[styles.tldrSection, { backgroundColor: theme.background }]}>
            <Text style={[styles.tldrLabel, { color: theme.textSecondary }]}>TL;DR</Text>
            <Text style={[styles.tldrText, { color: theme.text }]}>
              {summary.summary}
            </Text>
          </View>

          {/* Key Points */}
          {summary.keyPoints.length > 0 && (
            <View style={styles.keyPointsSection}>
              <Text style={[styles.keyPointsLabel, { color: theme.textSecondary }]}>
                Key Points
              </Text>
              {summary.keyPoints.map((point, index) => (
                <View key={index} style={styles.keyPoint}>
                  <View style={[styles.bullet, { backgroundColor: theme.primary }]} />
                  <Text style={[styles.keyPointText, { color: theme.text }]}>
                    {point}
                  </Text>
                </View>
              ))}
            </View>
          )}

          {/* Footer */}
          <View style={styles.footer}>
            <Text style={[styles.footerText, { color: theme.textSecondary }]}>
              {isAIGenerated ? `Generated by ${summary.model.split('/')[1] || 'AI'}` : 'Auto-generated summary'}
            </Text>
            {onGenerate && (
              <TouchableOpacity
                onPress={onGenerate}
                style={styles.refreshButton}
                hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}
              >
                <Ionicons name="refresh" size={16} color={theme.primary} />
                <Text style={[styles.refreshText, { color: theme.primary }]}>
                  Regenerate
                </Text>
              </TouchableOpacity>
            )}
          </View>
        </>
      )}
    </View>
  );
};

const styles = StyleSheet.create({
  card: {
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  loadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
    gap: 12,
  },
  loadingText: {
    fontSize: 14,
  },
  emptyContainer: {
    alignItems: 'center',
    paddingVertical: 20,
    gap: 12,
  },
  emptyText: {
    fontSize: 14,
  },
  generateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    gap: 6,
    marginTop: 8,
  },
  generateButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: '700',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  readingTimeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    gap: 4,
  },
  readingTimeText: {
    fontSize: 12,
    fontWeight: '600',
  },
  tldrSection: {
    padding: 12,
    borderRadius: 8,
    marginBottom: 12,
  },
  tldrLabel: {
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  tldrText: {
    fontSize: 15,
    lineHeight: 22,
  },
  keyPointsSection: {
    marginBottom: 12,
  },
  keyPointsLabel: {
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  keyPoint: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 8,
    gap: 10,
  },
  bullet: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginTop: 7,
  },
  keyPointText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.05)',
  },
  footerText: {
    fontSize: 11,
    fontStyle: 'italic',
  },
  refreshButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  refreshText: {
    fontSize: 12,
    fontWeight: '600',
  },
});

